routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();

Route::group(['middleware' => 'auth'],function(){

    //Reservs//
    Route::group(['prefix' => 'reservs', 'as' => 'reserv.'], function () {
        Route::get('/view/{slug}', 'ReservController@index')->name('view');
        Route::get('/create', 'ReservController@create')->name('create');
        Route::post('/save', 'ReservController@store')->name('save');
        Route::get('/show/{id}', 'ReservController@show')->name('show');
        Route::get('/edit/{id}', 'ReservController@edit')->name('edit');
        Route::post('/update', 'ReservController@update')->name('update');
        Route::get('/export/{id}', 'ReservController@exportPDF')->name('export');
        Route::post('/updateStatus', 'ReservController@updateStatus')->name('updateStatus');
        Route::post('/updateStatusAll', 'ReservController@updateStatusAll')->name('updateStatusAll');
        Route::post('/note', 'ReservController@storeNote')->name('note');

        //Calendar//
        Route::get('/events', 'ReservController@GetEvents')->name('events');

        //ห้องประชุมย่อยจาก Rooms//
        Route::post('/childrenroom', 'ReservController@GetChildrenRooms')->name('childrenroom');
    });

    //Rooms//
    Route::group(['prefix' => 'rooms', 'as' => 'room.'], function () {
        Route::get('/view', 'RoomController@index')->name('view');
        Route::get('/create', 'RoomController@create')->name('create');
        Route::post('/save', 'RoomController@store')->name('save');
        Route::get('/edit/{id}', 'RoomController@edit')->name('edit');
        Route::post('/update', 'RoomController@update')->name('update');
        Route::get('/remove/{id}', 'RoomController@destroy')->name('remove');
    });

    //Reports//
    Route::group(['prefix' => 'reports', 'as' => 'report.'], function () {
        Route::get('/view', 'ReportController@index')->name('view');
        Route::post('/report_year', 'ReportController@report_year')->name('reportyear');
        Route::post('/report_month', 'ReportController@report_month')->name('reportmonth');
        Route::post('/report_mannul', 'ReportController@report_mannul')->name('reportmannul');
    });

    //Users//
    Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
        Route::get('/view', 'UserController@index')->name('view');
        Route::get('/create', 'UserController@create')->name('create');
        Route::post('/save', 'UserController@store')->name('save');
        Route::get('/edit/{id}', 'UserController@edit')->name('edit');
        Route::post('/update/{id}', 'UserController@update')->name('update');
        Route::post('/active', 'UserController@active')->name('active');
        Route::get('/history/{id}', 'UserController@history')->name('history');
        Route::get('/editprofile/{id}', 'UserController@editProfile')->name('editprofile');
        Route::post('/updateprofile/{id}', 'UserController@updateProfile')->name('updateprofile');
        Route::get('/setpassword/{id}', 'UserController@setPassword')->name('setpassword');
        Route::post('/active', 'UserController@enabled')->name('active');
        Route::post('/inactive', 'UserController@disabled')->name('inactive');
    });

    //Configs//
    Route::group(['prefix' => 'set_basics', 'as' => 'set_basic.'], function () {
        Route::get('/view', 'Basic\SetBasicController@index')->name('view');

        //GroupUser//
        Route::group(['prefix' => 'groupusers', 'as' => 'groupuser.'], function () {
            Route::get('/view', 'Basic\GroupUserController@index')->name('view');
            Route::get('/create', 'Basic\GroupUserController@create')->name('create');
            Route::post('/save', 'Basic\GroupUserController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\GroupUserController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\GroupUserController@update')->name('update');
        });

        //Roles//
        Route::group(['prefix' => 'roles', 'as' => 'role.'], function () {
            Route::get('/view', 'Basic\RolesController@index')->name('view');
            Route::get('/create', 'Basic\RolesController@create')->name('create');
            Route::post('/save', 'Basic\RolesController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\RolesController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\RolesController@update')->name('update');
        });


    });

});

app/Rooms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rooms extends Model
{
    public $incrementing = false;

    protected $table = 'rooms';

    protected $fillable = [
        'id',
        'name',
        'desc',
        'num',
        'color',
        'images',
        'status_rooms_id',
        'children_code',
    ];

    public function StatusRoom()
    {
        return $this->belongsTo(StatusRooms::Class, 'status_rooms_id');
    }

    public function parent() {
        return $this->belongsTo(self::class, 'children_code');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children() {
        return $this->hasMany(Rooms::class, 'children_code');
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\ChildrenRooms;
use Illuminate\Http\Request;
use App\StatusRooms;
use App\Rooms;
use Storage;

class RoomController extends Controller
{
    protected $imagePath = 'images';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rooms = Rooms::with('StatusRoom')->get();

        return view('room.index', compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $chidrenrooms = Rooms::where('children_code', '=', '0')->get();
        $status = StatusRooms::get();

        return view('room.create', compact('status', 'chidrenrooms'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'num' => 'required',
            'status' => 'required',
            'color' => 'required',
        ],[
            'name.required' => 'กรุณากรอกชื่อห้อง',
            'num.required' => 'กรุณากรอกจำนวนคนในห้อง',
            'status.required' => 'กรุณาเลือกสถานะของห้อง',
            'color.required' => 'กรุณาเลือกสีของห้อง',
        ]);
        $uploadImages = null;
        try {
            $name = $request->get('name');
            $desc = $request->get('desc');
            $num = $request->get('num');
            $status = $request->get('status');
            $color = $request->get('color');
            $img = $request->get('img');
            $children_code = $request->get('children_code');
            //GetId//
            //return $children_code;
            $genId = $this->getId();

            $rooms = new Rooms;
            $rooms->id = $genId;
            $rooms->name = $name;
            $rooms->desc = $desc;
            $rooms->num = $num;
            $rooms->status_rooms_id = $status;
            $rooms->color = $color;
            $rooms->children_code  = $children_code;
            if($request->file('images') != null){
                $uploadImages = Storage::disk('storage')->put($this->imagePath, $img);
                $rooms->images = $uploadImages;
            }else{
                $rooms->images = "";
            }
            $rooms->save();
            //return $rooms;

            return redirect()->route('room.view')->with('success', 'บันทึกข้อมูลเรียบร้อยแล้ว');
        } catch (\Exception $exception) {
            if ($uploadImages != null) {
                Storage::disk('storage')->delete($this->imagePath . '/' . $img);
            }
            return redirect()->route('room.create')->with('error', $exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $rooms = Rooms::find($id);
            $chidrenrooms = Rooms::where('children_code', '=', '0')->get();
            $status = StatusRooms::get();

            return view('room.edit', compact('rooms', 'status', 'chidrenrooms'));
        } catch (\Exception $exception) {
            return redirect()->route('room.create')->with('error', $exception->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'num' => 'required',
            'status' => 'required',
            'color' => 'required',
        ],[
            'name.required' => 'กรุณากรอกชื่อห้อง',
            'num.required' => 'กรุณากรอกจำนวนคนในห้อง',
            'status.required' => 'กรุณาเลือกสถานะของห้อง',
            'color.required' => 'กรุณาเลือกสีของห้อง',
        ]);
        $uploadImages = null;
        try {
            $id = $request->get('id_rooms');
            $name = $request->get('name');
            $desc = $request->get('desc');
            $num = $request->get('num');
            $status = $request->get('status');
            $color = $request->get('color');
            $img = $request->get('img');
            $children_code = $request->get('children_code');

            $rooms = Rooms::find($id);
            $rooms->id = $id;
            $rooms->name = $name;
            $rooms->desc = $desc;
            $rooms->num = $num;
            $rooms->status_rooms_id = $status;
            $rooms->color = $color;
            $rooms->children_code  = $children_code;
            if($request->file('images') != null){
                $uploadImages = Storage::disk('storage')->put($this->imagePath, $img);
                $rooms->images = $uploadImages;
            }
            $rooms->save();

            return redirect()->route('room.view')->with('success', 'แก้ไขข้อมูลเรียบร้อยแล้ว');
        } catch (\Exception $exception) {
            if ($uploadImages != null) {
                Storage::disk('storage')->delete($this->imagePath . '/' . $img);
            }
            return redirect()->route('room.create')->with('error', $exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $room = Rooms::find($id);
        $room->delete();
        return redirect()->route('room.view')->with('success', 'ลบข้อมูลเรียบร้อยแล้ว');

    }


    public function getId()
    {
        $gen = Rooms::max('id');
        // Split string and number
        $numberLastid = substr($gen, 6);
        // Convert string number to integer
        $insertid = intval($numberLastid);
        // Zero-padded integer
        $stringInsertid = 'RVB' . sprintf("%05d", $insertid+1);

        return $stringInsertid;
    }
}

resources/views/room/create.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')

<div class="row">
	<div class="col-xs-12">
        <div class="page-header">
            <h1>สร้างห้องประชุม</h1>
        </div>
        <!--MessageAlert-->
        @include('flash_msg')
        <!--MessageAlert-->
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">สร้างห้องประชุม</div>
                <br>
                    <form class="form-horizontal" action="{{ route('room.save') }}"  method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name_room" class="col-sm-3 control-label">ชื่อห้อง</label>
                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="name" name="name" placeholder="" value="{{ old('name') }}">
                            </div>
                        </div>
                        <div class="form-group" style="color: red;">
                            <label class="col-sm-3 control-label">ห้องประชุมย่อย</label>
                            <div class="col-sm-5">
                                <select class="form-control" name="children_code">
                                    <option value="0">ไม่มีห้องประชุมย่อย</option>
                                    @foreach($chidrenrooms as $chidrenroom)
                                        <option value="{{ $chidrenroom->id }}">{{ $chidrenroom->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="desc_room" class="col-sm-3 control-label">รายละเอียดห้อง</label>
                            <div class="col-sm-6">
                                <textarea style="resize:none" rows="10" class="form-control" cols="50" id="desc" name="desc">{{ old('desc') }}</textarea>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('num') ? ' has-error' : '' }}">
                            <label for="num_room" class="col-sm-3 control-label">จำนวน</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="num" name="num" value="{{ old('num') }}">
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                            <label for="status_room" class="col-sm-3 control-label">สถานะห้อง</label>
                            <div class="col-sm-4">
                                <select class="form-control" id="status" name="status">
                                    <option value="">--- กรุณาเลือก ---</option>
                                    @foreach($status as $status)
                                    <option value="{{ $status->id }}">{{ $status->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('color') ? ' has-error' : '' }}">
                            <label for="color_room" class="col-sm-3 control-label">สีของห้อง</label>
                            <div class="col-sm-1">
                                <input type="color" class="form-control" id="color" name="color" value="{{ old('color') }}">
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('img') ? ' has-error' : '' }}">
                            <label for="img_room" class="col-sm-3 control-label">รูปห้อง</label>
                            <div class="col-sm-4">
                                <input type="file" class="form-control" id="img" name="img" onchange="readURL(this);">
                                <img id="img_room_preview">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                            <center><button type="submit" class="btn btn-primary" id="btn_create_room" name="btn_create_room">สร้างห้อง</button></center>
                            </div>
                        </div>
                    </form>

            </div>
        </div>

	</div><!-- /.col -->
</div><!-- /.row -->

@include('layouts.inc-minicontent-bottom')
@endsection
@section('scripts')
<script>
function readURL(input)
{
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#img_room_preview')
                .attr('src', e.target.result)
                .width(400)
                .height(300);
            };

            reader.readAsDataURL(input.files[0]);
    }
}

</script>
@endsection

resources/views/room/edit.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')

<div class="row">
	<div class="col-xs-12">
        <div class="page-header">
            <h1>แก้ไขห้องประชุม</h1>
        </div>
        <!--MessageAlert-->
        @include('flash_msg')
        <!--MessageAlert-->
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">แก้ไขห้องประชุม</div>
                <br>
                    <form class="form-horizontal" action="{{ route('room.update') }}"  method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name_room" class="col-sm-3 control-label">ชื่อห้อง</label>
                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="name" name="name" placeholder="" value="{{ $rooms->name }}">
                            </div>
                        </div>
                        <div class="form-group" style="color: red;">
                            <label class="col-sm-3 control-label">ห้องประชุมย่อย</label>
                            <div class="col-sm-5">
                                <select class="form-control" name="children_code">
                                    <option value="0">ไม่มีห้องประชุมย่อย</option>
                                    @foreach($chidrenrooms as $chidrenroom)
                                        <option value="{{ $chidrenroom->id }}" @if($rooms->children_code == $chidrenroom->id) selected @endif>{{ $chidrenroom->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="desc_room" class="col-sm-3 control-label">รายละเอียดห้อง</label>
                            <div class="col-sm-6">
                                <textarea style="resize:none" rows="10" class="form-control" cols="50" id="desc" name="desc">{{ $rooms->desc }}</textarea>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('num') ? ' has-error' : '' }}">
                            <label for="num_room" class="col-sm-3 control-label">จำนวน</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="num" name="num" value="{{ $rooms->num }}">
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                            <label for="status_room" class="col-sm-3 control-label">สถานะห้อง</label>
                            <div class="col-sm-4">
                                <select class="form-control" id="status" name="status">
                                    <option value="">--- กรุณาเลือก ---</option>
                                    @foreach($status as $status)
                                    <option value="{{ $status->id }}" @if($rooms->status_rooms_id == $status->id) selected @endif>{{ $status->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('color') ? ' has-error' : '' }}">
                            <label for="color_room" class="col-sm-3 control-label">สีของห้อง</label>
                            <div class="col-sm-1">
                                <input type="color" class="form-control" id="color" name="color" value="{{ $rooms->color }}">
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('img') ? ' has-error' : '' }}">
                            <label for="img_room" class="col-sm-3 control-label">รูปห้อง</label>
                            <div class="col-sm-4">
                                <input type="file" class="form-control" id="img" name="img" onchange="readURL(this);">
                                <img id="img_room_preview">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                            <input type="hidden" name="id_rooms" id="id_rooms" value="{{ $rooms->id }}">
                            <center><button type="submit" class="btn btn-primary" id="btn_edit_room" name="btn_edit_room">แก้ไขห้อง</button></center>
                            </div>
                        </div>
                    </form>

            </div>
        </div>

	</div><!-- /.col -->
</div><!-- /.row -->

@include('layouts.inc-minicontent-bottom')
@endsection
@section('scripts')
<script>
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#img_room_preview')
                .attr('src', e.target.result)
                .width(400)
                .height(300);
            };
            reader.readAsDataURL(input.files[0]);
    }
}
</script>
@endsection

resources/views/room/index.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')

<div class="row">
	<div class="col-xs-12">
		<div class="page-header">
			<h1>รายชื่อห้องประชุม</h1>
		</div>
		<!--MessageAlert-->
		@include('flash_msg')
		<!--MessageAlert-->
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<table class="table table-bordered table-striped">
				@foreach($rooms as $room)
					<tr>
						<th colspan="3">{{ $room->id }} : {{ $room->name }}</th>
					</tr>
					<tr>
						<td rowspan="2" width="15%">
							@if($room->images == NULL)
							 	<img src="{{ asset('images/no-image.png') }}" alt="" srcset="">
							@else
								<img src="" alt="" srcset="">
							@endif
						</td>
						<td colspan="3">รายละเอียด : {{ $room->desc }}</td>
					</tr>
					<tr height="35">
						<td>จำนวน : <strong>{{ $room->num }}</strong> ที่นั่ง</td>
						<td>สถานะ : {{ $room->StatusRoom->name }}</td>
					</tr>
					<tr>
						<td colspan="3"><button class="btn btn-white btn-info" type="button" onclick="window.location.href='{{ route('room.edit', $room->id) }}'"><i class="fa fa-pencil fa-fw"></i></button>
						&nbsp;<a class="btn btn-white btn-danger" href="#" onclick="window.location.href='{{ route('room.remove', $room->id) }}'" role="button"><i class="fa fa-trash-o fa-fw"></i></a></td>
					</tr>
				@endforeach
				</table>
			</div>
		</div>
	</div><!-- /.col -->
</div><!-- /.row -->

@include('layouts.inc-minicontent-bottom')
@endsection