routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();

Route::group(['middleware' => 'auth'],function(){

    //Reservs//
    Route::group(['prefix' => 'reservs', 'as' => 'reserv.'], function () {
        Route::get('/view/{slug}', 'ReservController@index')->name('view');
        Route::get('/create', 'ReservController@create')->name('create');
        Route::post('/save', 'ReservController@store')->name('save');
        Route::get('/show/{id}', 'ReservController@show')->name('show');
        Route::get('/edit/{id}', 'ReservController@edit')->name('edit');
        Route::post('/update', 'ReservController@update')->name('update');
        Route::get('/export/{id}', 'ReservController@exportPDF')->name('export');
        Route::post('/updateStatus', 'ReservController@updateStatus')->name('updateStatus');
        Route::post('/updateStatusAll', 'ReservController@updateStatusAll')->name('updateStatusAll');
        Route::post('/note', 'ReservController@storeNote')->name('note');

        //Calendar//
        Route::get('/events', 'ReservController@GetEvents')->name('events');

        //ห้องประชุมย่อยจาก Rooms//
        Route::post('/childrenroom', 'ReservController@GetChildrenRooms')->name('childrenroom');
    });

    //Rooms//
    Route::group(['prefix' => 'rooms', 'as' => 'room.'], function () {
        Route::get('/view', 'RoomController@index')->name('view');
        Route::get('/create', 'RoomController@create')->name('create');
        Route::post('/save', 'RoomController@store')->name('save');
        Route::get('/edit/{id}', 'RoomController@edit')->name('edit');
        Route::post('/update', 'RoomController@update')->name('update');
        Route::get('/remove/{id}', 'RoomController@destroy')->name('remove');
    });

    //Reports//
    Route::group(['prefix' => 'reports', 'as' => 'report.'], function () {
        Route::get('/view', 'ReportController@index')->name('view');
        Route::post('/report_year', 'ReportController@report_year')->name('reportyear');
        Route::post('/report_month', 'ReportController@report_month')->name('reportmonth');
        Route::post('/report_mannul', 'ReportController@report_mannul')->name('reportmannul');
    });

    //Users//
    Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
        Route::get('/view', 'UserController@index')->name('view');
        Route::get('/create', 'UserController@create')->name('create');
        Route::post('/save', 'UserController@store')->name('save');
        Route::get('/edit/{id}', 'UserController@edit')->name('edit');
        Route::post('/update/{id}', 'UserController@update')->name('update');
        Route::post('/active', 'UserController@active')->name('active');
        Route::get('/history/{id}', 'UserController@history')->name('history');
        Route::get('/editprofile/{id}', 'UserController@editProfile')->name('editprofile');
        Route::post('/updateprofile/{id}', 'UserController@updateProfile')->name('updateprofile');
        Route::get('/setpassword/{id}', 'UserController@setPassword')->name('setpassword');
        Route::post('/active', 'UserController@enabled')->name('active');
        Route::post('/inactive', 'UserController@disabled')->name('inactive');
    });

    //Configs//
    Route::group(['prefix' => 'set_basics', 'as' => 'set_basic.'], function () {
        Route::get('/view', 'Basic\SetBasicController@index')->name('view');

        //GroupUser//
        Route::group(['prefix' => 'groupusers', 'as' => 'groupuser.'], function () {
            Route::get('/view', 'Basic\GroupUserController@index')->name('view');
            Route::get('/create', 'Basic\GroupUserController@create')->name('create');
            Route::post('/save', 'Basic\GroupUserController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\GroupUserController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\GroupUserController@update')->name('update');
        });

        //Roles//
        Route::group(['prefix' => 'roles', 'as' => 'role.'], function () {
            Route::get('/view', 'Basic\RolesController@index')->name('view');
            Route::get('/create', 'Basic\RolesController@create')->name('create');
            Route::post('/save', 'Basic\RolesController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\RolesController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\RolesController@update')->name('update');
        });


    });

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'titles_id', 'fullname', 'group_users_id', 'email', 'password', 'roles_id', 'active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function Titles()
    {
        return $this->belongsTo(Titles::Class, 'titles_id');
    }

    public function Group()
    {
        return $this->belongsTo(GroupUsers::Class, 'group_users_id');
    }

    public function Role()
    {
        return $this->belongsTo(Roles::Class, 'roles_id');
    }   

    protected function routeNotificationForLine()
    {
       return 'FQrUgIoZqSgWruTPCrI9iJVM72IchWPoiolt5kyZjqN';
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Reserv;
use App\User;
use App\Titles;
use App\GroupUsers;
use App\Roles;
use App\Hasroles;
use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       try {
           $users = User::with('titles', 'group', 'role')->orderBy('id', 'asc')->paginate(20);
 
           return view('user.index', compact('users'));

       } catch (\Exception $exception) {
            return redirect()->route('user.view')->with('error', $exception->getMessage());
       }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $titles = Titles::get();
        $groupusers = GroupUsers::get();
        $roles = Roles::get();

        return view('user.create', compact('titles', 'groupusers', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'username' => 'required',
            'password' => 'required',
            'name' => 'required',
            'email' => 'required',
            'group_user' => 'required',
            'role' => 'required',
        ],[
            'title.required' => 'กรุณาระบุคำนำหน้าชื่อด้วยครับ',
            'username.required' => 'กรุณาระบุชื่อผู้ใช้งานด้วยครับ',
            'password.required' => 'กรุณาระบุรหัสผ่านด้วยครับ',
            'name.required' => 'กรุณาระบุชื่อ-นามสกุลด้วยครับ',
            'email.required' => 'กรุณาระบุอีเมล์ด้วยครับ',
            'group_user.required' => 'กรุณาระบุฝ่ายงานด้วยครับ',
            'role.required' => 'กรุณาระบุสิทธิ์ผู้ใช้งานด้วยครับ'
        ]);

        try {
            $title = $request->get('title');
            $name = $request->get('name');
            $username = $request->get('username');
            $password = $request->get('password');
            $email = $request->get('email');
            $group_user = $request->get('group_user');
            $role = $request->get('role');
            //CheckUserซ้ำ//
            $checkUser = User::where('username', '=', $username)->count();
            if($checkUser == 1){
                return redirect()->route('user.view')->with('error', 'มีชื่อผู้ใช้งานอยู่ระบบแล้ว กรุณาเปลี่ยนเป็นชื่อผู้ใช้งานอื่น');
            }else{
                $user = new User;
                $user->username = $username;
                $user->titles_id = $title;
                $user->fullname = $name;
                $user->group_users_id = $group_user;
                $user->email = $email;
                $user->password = Hash::make($password);
                $user->roles_id = $role;
                $user->active = 1;
                $user->save();

                return redirect()->route('user.view')->with('success', 'บันทึกข้อมูลเรียบร้อยแล้ว');
            }
            
        } catch (\Exception $exception) {

            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $edituser = User::with(['Group','Role','Titles'])->find($id);
            $titles = Titles::get();
            $groupusers = GroupUsers::get();
            $roles = Roles::get();

            return view('user.edit',compact('edituser','titles','groupusers','roles'));
        } catch (\Exception $exception) {
            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' => 'required',
            'username' => 'required',
            'name' => 'required',
            'email' => 'required',
            'group_user' => 'required',
            'role' => 'required',
        ],[
            'title.required' => 'กรุณาระบุคำนำหน้าชื่อด้วยครับ',
            'username.required' => 'กรุณาระบุชื่อผู้ใช้งานด้วยครับ',
            'name.required' => 'กรุณาระบุชื่อ-นามสกุลด้วยครับ',
            'email.required' => 'กรุณาระบุอีเมล์ด้วยครับ',
            'group_user.required' => 'กรุณาระบุฝ่ายงานด้วยครับ',
            'role.required' => 'กรุณาระบุสิทธิ์ผู้ใช้งานด้วยครับ'
        ]);

        try {
            $user = User::find($id);
            if(!$user)
            {
                return trans('app.invalid_request');
            }
            $user->titles_id = $request->input('title');
            $user->username = $request->input('username');
            if($request->input('new_password') != $request->input('confirm_password'))
            {
                if(empty($request->input('confirm_password')))
                {
                    return redirect()->back()->with('error', 'กรุณายืนยันรหัสผ่านด้วย');
                }
                return redirect()->back()->with('error', 'กรุณาระบุรหัสผ่านให้ตรงกัน');
            }
            if(!empty($request->input('new_password'))){
                $user->password = Hash::make($request->input('new_password'));
            }
            $user->fullname = $request->input('name');
            $user->email = $request->input('email');
            $user->group_users_id = $request->input('group_user');
            $user->roles_id = $request->input('role');
            $user->save();

            return redirect()->route('user.view')->with('success', 'แก้ไขข้อมูลผู้ใช้งานเรียบร้อยแล้ว');

        } catch (\Exception $exception) {
            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function enabled(Request $request)
    {
        try{
            $user = User::find($request->get('id'));
            $user->active = 0;
            $user->save();
            
            return response()->json(['status' => true]);
        }catch(\Exception $exception){
            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }


    public function disabled(Request $request)
    {
        try{
            $user = User::find($request->get('id'));
            $user->active = 1;
            $user->save();
            
            return response()->json(['status' => true]);
        }catch(\Exception $exception){
            
            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }


    public function history($id)
    {
        try {
            $history = Reserv::with('status', 'user', 'room')->where('user_id', Auth::user()->id)->orderBy('id', 'asc')->paginate(10);

            return view('user.history', compact('history'));
        } catch (\Exception $exception) {

            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }

    public function editProfile($id)
    {
        try {
            $titles = Titles::get();
            $groupusers = GroupUsers::get();

            $profiles = User::find($id);

            return view('user.profile', compact('profiles', 'titles', 'groupusers'));
        } catch (\Exception $exception) {

            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }

    public function updateProfile(Request $request,$id)
    {
        try {
            $user = User::find($id);
            if(!$user)
            {
                return trans('app.invalid_request');
            }
            $user->titles_id = $request->input('title');
            $user->username = $request->input('username');
            if($request->input('new_password') != $request->input('confirm_password'))
                {
                    if(empty($request->input('confirm_password')))
                    {
                        return redirect()->back()->with('error', 'กรุณายืนยันรหัสผ่านด้วย');
                    }
                    return redirect()->back()->with('error', 'กรุณาระบุรหัสผ่านให้ตรงกัน');
                }
            if(!empty($request->input('new_password'))){
                $user->password = Hash::make($request->input('new_password'));
            }
            $user->fullname = $request->input('name');
            $user->email = $request->input('email');
            $user->group_users_id = $request->input('groupuser');
            $user->save();

            return redirect()->back()->with('success', 'แก้ไขข้อมูลส่วนตัวเรียบร้อยแล้ว');
        } catch (\Exception $exception) {
            
            return redirect()->route('user.view')->with('error', $exception->getMessage());
        }
    }

    public function setPassword($id)
    {
        try{
            $user = User::find($id);
            if(!$user)
            {
                return trans('app.invalid_request');
            }
            $user->password = Hash::make('123456');
            $user->save();

            return redirect()->back()->with('success', 'ตั้งรหัสผ่าน 123456 เรียบร้อยแล้ว');
        } catch(\Exception $exception) {

resources/views/user/create.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')

<div class="col-md-12">
    <div class="page-header">
        <h1>สร้างบัญชีผู้ใช้งาน</h1>
    </div>

	<!--MessageAlert-->
    @include('flash_msg')
    <!--MessageAlert-->

    <div class="col-md-6 col-md-offset-3">

    <div class="panel panel-danger">
        <div class="panel-heading"><i class="fa fa-user-o" aria-hidden="true"></i> สร้างบัญชีผู้ใช้งาน</div>
        <div class="panel-body">
            <form action="{{ route('user.save') }}" method="post" class="form-horizontal">
            {{ csrf_field() }}
            <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
                <label for="title" class="col-sm-2 control-label">คำนำหน้า</label>
                <div class="col-sm-4">
                    <select class="form-control" name="title" id="title">
                        <option value="">--- กรุณาเลือก ---</option>
                        @foreach($titles as $title)
                        <option value="{{ $title->id }}">{{ $title->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-sm-2 control-label">ชื่อ-นามสกุล</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                </div>
            </div>
            <div class="form-group {{ $errors->has('username') ? ' has-error' : '' }}">
                <label for="username" class="col-sm-2 control-label">ชื่อผู้ใช้งาน</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="username" name="username" placeholder="Username">
                </div>
            </div>
            <div class="form-group {{ $errors->has('password') ? ' has-error' : '' }}">
                <label for="password" class="col-sm-2 control-label">รหัสผ่าน</label>
                <div class="col-sm-8">
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                </div>
            </div>
            <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email" class="col-sm-2 control-label">อีเมล์</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="email" name="email" placeholder="Email">
                </div>
            </div>
            <div class="form-group {{ $errors->has('group_user') ? ' has-error' : '' }}">
                <label for="group_user" class="col-sm-2 control-label">ฝ่าย</label>
                <div class="col-sm-8">
                    <select class="form-control" name="group_user" id="group_user">
                        <option value="">--- กรุณาเลือกฝ่าย ---</option>
                        @foreach($groupusers as $groupuser)
                        <option value="{{ $groupuser->id }}">{{ $groupuser->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group {{ $errors->has('role') ? ' has-error' : '' }}">
                <label for="role" class="col-sm-2 control-label">สิทธิ์</label>
                <div class="col-sm-6">
                    <select class="form-control" id="role" name="role">
                    <option value="">--- กรุณาเลือก ---</option>
                    @foreach($roles as $role)
                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                    @endforeach
                    </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-5 col-sm-10">
                    <button type="submit" class="btn btn-success" id="btn_save_user"><span class="glyphicon glyphicon-floppy-disk"></span> สร้าง</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>


@include('layouts.inc-minicontent-bottom')
@endsection

resources/views/user/edit.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')

<div class="col-lg-12">
    <div class="page-header">
        <h1>แก้ไขข้อมูลผู้ใช้งาน</h1>
    </div>

	<!--MessageAlert-->
	@include('flash_msg')
    <!--MessageAlert-->

    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-success">
            <div class="panel-heading"><span class="glyphicon glyphicon-pencil"></span>แก้ไขข้อมูลผู้ใช้งาน</div>
        <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{{ route('user.update',$edituser->id) }}">
            {{ csrf_field() }}
                <div class="form-group">
                    <label for="edit_title" class="col-sm-2 control-label">คำนำหน้า </label>
                    <div class="col-sm-5">
                        <select class="form-control" name="title" id="title">
                        <option value="">--- กรุณาเลือก ---</option>
                        @foreach($titles as $title)
                            <option value="{{ $title->id }}" @if($edituser->titles_id == $title->id) selected="selected" @endif >{{ $title->name }}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="edit_name_log" class="col-sm-2 control-label">ชื่อ-นามสกุล</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="name" name="name" value="{{ $edituser->fullname }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="edit_username_log" class="col-sm-2 control-label">ชื่อผู้ใช้งาน</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="username" name="username" value="{{ $edituser->username }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="edit_email_log" class="col-sm-2 control-label">อีเมล์</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="email" name="email" value="{{ $edituser->email }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="edit_group_user" class="col-sm-2 control-label">ฝ่าย </label>
                    <div class="col-sm-5">
                        <select class="form-control" name="group_user" id="group_user">
                        <option value="">--- กรุณาเลือกฝ่าย ---</option>
                        @foreach($groupusers as $groupUser)
                            <option value="{{ $groupUser->id }}" @if($edituser->group_users_id == $groupUser->id) selected="selected" @endif >{{ $groupUser->name }}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">   
                    <label for="edit_role" class="col-sm-2 control-label">สิทธิ์</label>
                    <div class="col-sm-4">     
                        <select class="form-control" id="role" name="role">
                        <option value="">--- กรุณาเลือก ---</option>
                        @foreach($roles as $role)
                            <option value="{{ $role->id }}" @if($edituser->roles_id == $role->id) selected="selected" @endif >{{ $role->name }}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
                <div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-10">
                        <input type="hidden" id="id_user" name="id_user" value="{{ $edituser->id }}">
                        <button type="submit" class="btn btn-success" id="btn_edit_member"><span class="glyphicon glyphicon-floppy-disk"></span> แก้ไขข้อมูล</button>
                    </div>
                </div>
                </form>
        </div>
        </div>

    </div>

</div>

@include('layouts.inc-minicontent-bottom')
@endsection

resources/views/user/history.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')
<div class="col-md-12">
    <div class="page-header">
        <h1><i class="fa fa-history" aria-hidden="true"></i>&nbsp;ประวัติการจอง</h1>
    </div>

    <table class="table table-striped table-bordered" cellspacing="0">
        <tr>
            <th width="2%">เลขที่จอง</th>
            <th width="5%">สถานะ</th>
            <th width="15%">หัวข้อประชุม</th>
            <th width="15%">ห้องประชุม</th>
            <th width="10%">วันที่-เวลาจอง</th>
            <th width="10%">วันที่-เวลาสิ้นสุด</th>
            <th width="8%" align="center">&nbsp;</th>
        </tr>
        @foreach($history as $key => $his)
        <tr>
            <td>{{ $his->id }}</td>
            <td><font color="@if($his->status->id == 1) #A0522D @elseif($his->status->id == 2) #5cb85c @elseif($his->status->id == 3) #d9534f @endif">
                    @if($his->status->id == 1)
                        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>
                    @elseif($his->status->id == 2)
                        <i class="fa fa-check-square" aria-hidden="true"></i>
                    @elseif($his->status->id == 3)
                        <i class="fa fa-times-circle" aria-hidden="true"></i>
                    @endif
                    {{ $his->status->name }}</font></td>
            <td>{{ $his->topic }}</td>
            <td>{{ $his->room->name }}</td>
            <td>{{ ConvertDate($his->startday) }} <br> {{ ConvertTime($his->starttime) }}&nbsp;น.</td>
            <td>{{ ConvertDate($his->endday) }} <br> {{ ConvertTime($his->endtime) }}&nbsp;น.</td>
            <td><center><button class="btn btn-app btn-info btn-xs" onclick="javascript:window.location.href='{{ route('reserv.show',$his->id) }}'">
            <i class="ace-icon fa fa-info bigger-120"></i>ดูข้อมูล</button></center></td>
        </tr>
        @endforeach
    </table>
    <p>ทั้งหมด {{ $history->total() }} รายการ</p>
    {{ $history->links() }}

@include('layouts.inc-minicontent-bottom')
@endsection

resources/views/user/index.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')

<div class="row">
    <div class="col-xs-12">

        <div class="page-header">
			<h1>รายชื่อผู้ใช้งาน</h1>
        </div>

		<!--MessageAlert-->
		@include('flash_msg')
        <!--MessageAlert-->
        

        <table class="table table-bordered">
            <tr>
                <th width="2%">ลำดับที่</th>
                <th width="13%">ชื่อ-นามสกุล</th>
                <th width="8%">ชื่อผู้ใช้งาน</th>
                <th width="8%">ฝ่าย</th>
                <th width="5%">สิทธิ์ผู้ใช้งาน</th>
                <th width="20%">&nbsp;</th>
            </tr>
            @foreach($users as $row => $user)
            <tr>
                <td>{{ $users->firstItem() + $row }}</td>
                <td>{{ $user->titles->name }} {{ $user->fullname }}</td>
                <td>{{ $user->username }}</td>
                <td>{{ $user->group->name }}</td>
                <td>{{ $user->role->name }}</td>
                @php
                    $icon_button;
                    $text_button;
                    $color_button;
                    $function_button;
                    if($user->active == 1){
                        $icon_button = "lock";
                        $text_button = "ปิดการใช้งาน";
                        $color_button = "danger";
                        $function_button = "inactiveUser";
                    }elseif($user->active == 0){
                        $icon_button = "unlock";
                        $text_button = "เปิดการใช้งาน";
                        $color_button = "success";
                        $function_button = "activeUser";                    
                    }
                @endphp                
                <td>
                    <a class="btn btn-info" href="{{ route('user.edit', $user->id) }}" role="button"><i class="fa fa-pencil fa-fw"></i>&nbsp;แก้ไขข้อมูล</a>
                    <button class="btn btn-{{ $color_button }}" href="#" onclick="{{ $function_button }}('{{ $user->id }}')" role="button"><i class="fa fa-{{ $icon_button }} fa-fw"></i>{{ $text_button }}</button>
                    <a class="btn btn-warning" href="{{ route('user.setpassword', $user->id) }}" onclick="" role="button">ตั้งรหัสผ่านใหม่ 123456</a>
                </td>
            </tr>
            @endforeach
        </table>
        <p>ทั้งหมด {{ $users->total() }} รายการ</p>
        {{ $users->links() }}
    </div>
</div>

@include('layouts.inc-minicontent-bottom')
@endsection
@section('scripts')
    <script>
        function activeUser(id){
            $.ajax({
                type: "POST",
                url: "{{ route('user.inactive') }}",
                data: {
                    id : id,
                    _token : "{{ csrf_token() }}"
                },
                success: function(data){
                    if(data.status == true){
                        swal("เปิดการใช้งานเรียบร้อยแล้ว","","success")
                            .then(function(){ 
                            window.location.reload();
                        });
                    }
                }
            });
        }
        function inactiveUser(id){
            $.ajax({
                type: "POST",
                url: "{{ route('user.active') }}",
                data: {
                    id : id,
                    _token : "{{ csrf_token() }}"
                },
                success: function(data){
                    if(data.status == true){
                        swal("ปิดการใช้งานเรียบร้อยแล้ว","","success")
                            .then(function(){ 
                            window.location.reload();
                        });                        
                    }
                }
            });
        }
    </script>

@endsection