routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();

Route::group(['middleware' => 'auth'],function(){

    //Reservs//
    Route::group(['prefix' => 'reservs', 'as' => 'reserv.'], function () {
        Route::get('/view/{slug}', 'ReservController@index')->name('view');
        Route::get('/create', 'ReservController@create')->name('create');
        Route::post('/save', 'ReservController@store')->name('save');
        Route::get('/show/{id}', 'ReservController@show')->name('show');
        Route::get('/edit/{id}', 'ReservController@edit')->name('edit');
        Route::post('/update', 'ReservController@update')->name('update');
        Route::get('/export/{id}', 'ReservController@exportPDF')->name('export');
        Route::post('/updateStatus', 'ReservController@updateStatus')->name('updateStatus');
        Route::post('/updateStatusAll', 'ReservController@updateStatusAll')->name('updateStatusAll');
        Route::post('/note', 'ReservController@storeNote')->name('note');

        //Calendar//
        Route::get('/events', 'ReservController@GetEvents')->name('events');

        //ห้องประชุมย่อยจาก Rooms//
        Route::post('/childrenroom', 'ReservController@GetChildrenRooms')->name('childrenroom');
    });

    //Rooms//
    Route::group(['prefix' => 'rooms', 'as' => 'room.'], function () {
        Route::get('/view', 'RoomController@index')->name('view');
        Route::get('/create', 'RoomController@create')->name('create');
        Route::post('/save', 'RoomController@store')->name('save');
        Route::get('/edit/{id}', 'RoomController@edit')->name('edit');
        Route::post('/update', 'RoomController@update')->name('update');
        Route::get('/remove/{id}', 'RoomController@destroy')->name('remove');
    });

    //Reports//
    Route::group(['prefix' => 'reports', 'as' => 'report.'], function () {
        Route::get('/view', 'ReportController@index')->name('view');
        Route::post('/report_year', 'ReportController@report_year')->name('reportyear');
        Route::post('/report_month', 'ReportController@report_month')->name('reportmonth');
        Route::post('/report_mannul', 'ReportController@report_mannul')->name('reportmannul');
    });

    //Users//
    Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
        Route::get('/view', 'UserController@index')->name('view');
        Route::get('/create', 'UserController@create')->name('create');
        Route::post('/save', 'UserController@store')->name('save');
        Route::get('/edit/{id}', 'UserController@edit')->name('edit');
        Route::post('/update/{id}', 'UserController@update')->name('update');
        Route::post('/active', 'UserController@active')->name('active');
        Route::get('/history/{id}', 'UserController@history')->name('history');
        Route::get('/editprofile/{id}', 'UserController@editProfile')->name('editprofile');
        Route::post('/updateprofile/{id}', 'UserController@updateProfile')->name('updateprofile');
        Route::get('/setpassword/{id}', 'UserController@setPassword')->name('setpassword');
        Route::post('/active', 'UserController@enabled')->name('active');
        Route::post('/inactive', 'UserController@disabled')->name('inactive');
    });

    //Configs//
    Route::group(['prefix' => 'set_basics', 'as' => 'set_basic.'], function () {
        Route::get('/view', 'Basic\SetBasicController@index')->name('view');

        //GroupUser//
        Route::group(['prefix' => 'groupusers', 'as' => 'groupuser.'], function () {
            Route::get('/view', 'Basic\GroupUserController@index')->name('view');
            Route::get('/create', 'Basic\GroupUserController@create')->name('create');
            Route::post('/save', 'Basic\GroupUserController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\GroupUserController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\GroupUserController@update')->name('update');
        });

        //Roles//
        Route::group(['prefix' => 'roles', 'as' => 'role.'], function () {
            Route::get('/view', 'Basic\RolesController@index')->name('view');
            Route::get('/create', 'Basic\RolesController@create')->name('create');
            Route::post('/save', 'Basic\RolesController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\RolesController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\RolesController@update')->name('update');
        });


    });

});

app/Reserv.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Reserv extends Model
{
    use Notifiable;

    public $incrementing = false;
    protected $table = "reservs";
    protected $fillable = [
        'startday',
        'endday',
        'starttime',
        'endtime',
        'rooms_id',
        'types_id',
        'topic',
        'desc',
        'num',
        'namejoin',
        'tel',
        'check_catering',
        'txt_catering2',
        'txt_cateringother',
        'check_projector',
        'check_screen',
        'check_dvd',
        'check_tv',
        'check_record',
        'check_amp',
        'check_control',
        'txt_control',
        'check_wireless_mic',
        'txt_wireless_mic',
        'check_mic',
        'txt_mic',
        'check_other',
        'txt_other',
        'status_reservs_id',
        'create_date',
        'position_reservs_id',
        'user_id',
        'note',
        'note_position_reserv'
    ];


    public function Status()
    {
        return $this->belongsTo(StatusReservs::Class, 'status_reservs_id');
    }

    public function User()
    {
        return $this->belongsTo(User::Class, 'user_id');
    }

    public function Room()
    {
        return $this->belongsTo(Rooms::Class, 'rooms_id');
    }

    public function Position()
    {
        return $this->belongsTo(PositionReservs::Class, 'position_reservs_id');
    }

    public function RoomsReserv()
    {
        return $this->hasMany(RoomReservs::class, 'reservs_id')->with('room');
    }

    protected function routeNotificationForLine()
    {
        return 'FQrUgIoZqSgWruTPCrI9iJVM72IchWPoiolt5kyZjqN';
    }
}

app/Http/Controllers/ReservController.php
<?php

namespace App\Http\Controllers;

use App\RoomReservs;
use Illuminate\Http\Request;
use App\Rooms;
use App\TypesReserv;
use App\PositionReservs;
use App\Reserv;
use App\User;
use Auth;
use Intervention\Image\Facades\Image;
use PDF;
use Calendar;
use App\StatusReservs;
use App\Notifications\ReservNotification;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ReservController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $slug)
    {
        if($slug == 'today'){
            $rooms = Rooms::get();

            return view('reserv.index_today', compact('rooms'));
        }else if($slug == 'calendar'){

            return view('reserv.index_calendar');
        }else if($slug == 'table'){

            $users = User::get();
            $statuss = StatusReservs::get();

            if($request->get('id_no') != ""){
                $reservs = Reserv::with('status', 'user')->where('id', 'LIKE', '%'.$request->get('id_no').'%')->paginate(20);
            }else if($request->get('topic') != ""){
                $reservs = Reserv::with('status', 'user')->where('topic', 'LIKE', '%'.$request->get('topic').'%')->paginate(20);
            }else if($request->get('user') != ""){
                $reservs = Reserv::with('status', 'user')->where('user_id', $request->get('user'))->paginate(20);
            }else if($request->get('date_reserv') != ""){
                $reservs = Reserv::with('status', 'user')->where('created_at', 'LIKE', '%'.$request->get('date_reserv').'%')->paginate(20);
            }else if($request->get('status') != ""){
                $reservs = Reserv::with('status', 'user')->where('status_reservs_id', 'LIKE', '%'.$request->get('status').'%')->paginate(20);
            }else {
                $reservs = Reserv::with('status', 'user')->orderBy('id', 'DESC')->paginate(20);
            }

            return view('reserv.index_table', compact('reservs', 'users', 'statuss'))->with("reservs", $reservs);
        }
    }

    public function create()
    {
        $rooms = Rooms::where('children_code', '0')->get();
        $chidren_rooms = Rooms::where('children_code', '!=', '0')->get();
        $types = TypesReserv::get();
        $positions = PositionReservs::get();

        return view('reserv.create', compact('rooms', 'types', 'positions', 'chidren_rooms'));
    }

    public function store(Request $request)
    {
        Log::info($request);
        $this->validate($request,[
            'startday' => 'required',
            'startmonth' => 'required',
            'startyear' => 'required',
            'endday' => 'required',
            'endmonth' => 'required',
            'endyear' => 'required',
            'starttime' => 'required',
            'endtime' => 'required',
            'room' => 'required',
            'typereserv' => 'required',
            'topic' => 'required',
            'num' => 'required',
            'tel' => 'required',
            'check_catering' => 'required',
            'position_reserv' => 'required'
        ],[
            'startday.required' => 'กรุณาเลือกวันที่เริ่มต้น',
            'startmonth.required' => 'กรุณาเลือกเดือนที่เริ่มต้น',
            'startyear.required' => 'กรุณาเลือกปีที่เริ่มต้น',
            'endday.required' => 'กรุณาเลือกวันที่สิ่้นสุด',
            'endmonth.required' => 'กรุณาเลือกเดือนที่สิ้นสุด',
            'endyear.required' => 'กรุณาเลือกปีที่สิ้นสุด',
            'starttime.required' => 'กรุณาเลือกเวลาที่เริ่มต้น',
            'endtime.required' => 'กรุณาเลือกเวลาที่สิ้นสุด',
            'room.required' => 'กรุณาเลือกห้องประชุม',
            'typereserv.required' => 'กรุณาเลือกประเภทของการประชุม',
            'topic.required' => 'กรุณากรอกหัวข้อการประชุม',
            'num.required' => 'กรุณากรอกจำนวนผู้เข้าประชุม',
            'tel.required' => 'กรุณากรอกเบอร์ติดต่อ',
            'check_catering.required' => 'กรุณาเลือกอุปกรณ์จัดอาหาร',
            'position_reserv.required' => 'กรุณาเลือกรูปแบบการจัดห้องประชุม'
        ]);
        try {
            $str_startday = $request->get('startday');
            $str_startmonth = $request->get('startmonth');
            $str_startyear = $request->get('startyear');
            $convert_startdate = ($str_startyear-543)."-".$str_startmonth."-".$str_startday;
            $str_starttime = $request->get('starttime');

            $str_endday = $request->get('endday');
            $str_endmonth = $request->get('endmonth');
            $str_endyear = $request->get('endyear');
            $convert_enddate = ($str_endyear-543)."-".$str_endmonth."-".$str_endday;

            $str_endtime = $request->get('endtime');

            $str_room = $request->get('room');
            $str_children_room = $request->get('ch_children_room');

            $str_typereserv = $request->get('typereserv');
            $str_topic = $request->get('topic');
            $str_desc = $request->get('desc');
            $str_num = $request->get('num');
            $str_namejoin = $request->get('namejoin');
            $str_tel = $request->get('tel');
            $str_check_catering = $request->get('check_catering');
            $str_txt_catering2 = $request->get('txt_catering2');
            $str_txt_cateringother = $request->get('txt_cateringother');
            $str_check_projector = $request->get('check_projector');
            $str_check_screen = $request->get('check_screen');
            $str_check_dvd = $request->get('check_dvd');
            $str_check_tv = $request->get('check_tv');
            $str_check_record = $request->get('check_record');
            $str_check_amp = $request->get('check_amp');
            $str_check_control = $request->get('check_control');
            $str_txt_control = $request->get('txt_control');
            $str_check_wireless_mic = $request->get('check_wireless_mic');
            $str_txt_wireless_mic = $request->get('txt_wireless_mic');
            $str_check_mic = $request->get('check_mic');
            $str_txt_mic = $request->get('txt_mic');
            $str_check_other = $request->get('check_other');
            $str_txt_other = $request->get('txt_other');
            $str_position_reserv = $request->get('position_reserv');
            $str_txt_table_reserv = $request->get('txt_tableReserv');

            Log::info('reserv user: '.$request);
            //CheckRoomซ้ำวันจอง//

            $children_room = '';
            if(is_array($str_children_room))
                $children_room = implode(',', $str_children_room);

            $check_reserv = DB::select("
            SELECT *
                FROM reservs
                WHERE rooms_id IN
                (
                 SELECT
                  rooms.id
                 FROM
                  rooms
                  LEFT OUTER JOIN
                    room_reservs on reservs.id = room_reservs.reservs_id
                 WHERE
                        (startday BETWEEN '".$convert_startdate."' AND '".$convert_enddate."')
                        OR
                        (endday BETWEEN '".$convert_startdate."' AND '".$convert_enddate."')
                        OR
                        ('".$convert_startdate."' BETWEEN startday AND endday)
                        OR
                        ('".$convert_enddate."' BETWEEN startday AND endday)
                  AND
                  (
                        (starttime BETWEEN '".$str_starttime."' AND '".$str_endtime."')
                        OR
                        (endtime BETWEEN '".$str_starttime."' AND '".$str_endtime."')
                        OR
                        ('".$str_starttime."' BETWEEN starttime AND endtime)
                        OR
                        ('".$str_endtime."' BETWEEN starttime AND endtime)
                  )
                  AND room_reservs.room_id IN ('".$children_room."')
                )
                AND rooms_id = '".$str_room."'
                AND status_reservs_id != '3'
            ");

            $cnt_reserv = count($check_reserv);
            if($cnt_reserv >= 1){
                Log::info($check_reserv);
                return redirect()->route('reserv.create')->with('error','ไม่สามารถจองห้องได้ เนื่องจากห้องถูกจองใช้งานไปแล้ว กรุณาเลือกวัน/เวลาจองอื่น');
            }else{
                //GenId//
                $genId = $this->genCode();

                $reserv = new Reserv;
                $reserv->id = $genId;
                $reserv->startday = $convert_startdate;
                $reserv->endday = $convert_enddate;
                $reserv->starttime = $str_starttime;
                $reserv->endtime = $str_endtime;
                $reserv->rooms_id = $str_room;
                $reserv->types_id = $str_typereserv;
                $reserv->topic = $str_topic;
                $reserv->desc = $str_desc;
                $reserv->num = $str_num;
                $reserv->namejoin = $str_namejoin;
                $reserv->tel = $str_tel;
                $reserv->check_catering = $str_check_catering;
                $reserv->txt_catering2 = $str_txt_catering2;
                $reserv->txt_cateringother = $str_txt_cateringother;
                $reserv->check_projector = $str_check_projector;
                $reserv->check_screen = $str_check_screen;
                $reserv->check_dvd = $str_check_dvd;
                $reserv->check_tv = $str_check_tv;
                $reserv->check_record = $str_check_record;
                $reserv->check_amp = $str_check_amp;
                $reserv->check_control = $str_check_control;
                $reserv->txt_control = $str_txt_control;
                $reserv->check_wireless_mic = $str_check_wireless_mic;
                $reserv->txt_wireless_mic = $str_txt_wireless_mic;

resources/views/reserv/inc-tab.blade.php
<ul class="nav nav-tabs" id="myTabs" role="tablist">
    <li role="presentation" class="{{ Request::is('reservs/view/today') ? 'active' : '' }}">
        <a href="{{ url('reservs/view/today') }}" id="event_today-tab"aria-controls="event_today" aria-expanded="false"><i class="fa fa-calendar-minus-o" aria-hidden="true"></i>&nbsp;รายการจองวันนี้</a>
    </li>                                 
    <li role="presentation" class="{{ Request::is('reservs/view/calendar') ? 'active' : '' }}">
        <a href="{{ url('reservs/view/calendar') }}" id="event_list-tab" aria-controls="event_list" aria-expanded="false"><i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;ข้อมูลแบบปฏิทิน</a>
    </li> 
    <li role="presentation" class="{{ Request::is('reservs/view/table') ? 'active' : '' }}">
        <a href="{{ url('reservs/view/table') }}" id="event_table-tab" aria-expanded="false"><span class="glyphicon glyphicon-list"></span>&nbsp;ข้อมูลแบบตาราง</a>
    </li>
</ul>

resources/views/reserv/index_table.blade.php
@extends('layouts.layout')

@section('title', 'ระบบจองห้องประชุมสำนักงานอาสากาชาด')

@section('content')

@include('layouts.inc-menu')
@include('layouts.inc-minicontent-top')
@section('stylesheets')
    <link id="bsdp-css" href="{{ asset('css/datepicker.css') }}" rel="stylesheet">
@endsection
<div class="row">
	<div class="col-xs-12">
        <div class="page-header">
            <h1>รายการการใช้ห้องประชุม</h1>
        </div>
		<!--MessageAlert-->
        @include('flash_msg')
        <!--MessageAlert-->
        @include('reserv.inc-tab')
        <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade active in" role="tabpanel" id="event_today" aria-labelledby="event_today-tab">

                <form class="form-inline" action="{{ route('reserv.view', [$slug = 'table']) }}" method="get">
                    {{ csrf_field() }}
                    <div class="row">

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="id_no">เลขที่จอง :</label>
                                <input type="text" name="id_no" id="id_no" value="{{ old('id_no') }}">
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="topic">หัวข้อประชุม :</label>
                                <input type="text" name="topic" id="topic" value="{{ old('topic') }}">
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="user">ชื่อผู้จอง :</label>
                                <select name="user" id="user" onchange="this.form.submit()">
                                    <option value="">--- กรุณาเลือก ---</option>
                                    @foreach($users as $user)
                                    <option value="{{ $user->id }}">{{ $user->titles->name }} {{ $user->fullname }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="date_reserv">วันที่จอง :</label>
                                <input class="form-control date-picker" id="date_reserv" name="date_reserv" type="text" data-date-format="dd-mm-yyyy" value="{{ old('date_reserv') }}" autocomplete="off" />
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="topic">สถานะ :</label>
                                <select name="status" id="status" onchange="this.form.submit()">
                                <option value="">--- กรุณาเลือก ---</option>
                                    @foreach($statuss as $status)
                                        <option value="{{ $status->id }}">{{ $status->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <button type="submit" id="btn_search_data" onclick="" class="btn btn-success"><span class="glyphicon glyphicon-search"></span>&nbsp;ค้นหา</button>
                        </div>
                    </div>
                </form>
                <hr>
                <div class="clearfix"></div>
                    @if(Auth::user()->roles_id == 1 || Auth::user()->roles_id == 2)
                    <button style="margin-bottom: 10px;display: none;" class="btn btn-danger delete_all" data-url="{{ url('myproductsDeleteAll') }}">ยืนยันการจอง</button>
                    @endif
                <table class="table table-striped table-bordered">
                    <tr>
                        @if(Auth::user()->roles_id == 1 || Auth::user()->roles_id == 2)
                        <th width="1%">
                            <div class="form-group">
                            <input type="checkbox" id="all_chk" class="minimal">
                            </div>
                        </th>
                        @endif
                        <th width="5%">เลขที่จอง</th>
                        <th width="5%">สถานะ</th>
                        <th width="15%">หัวข้อประชุม</th>
                        <th width="10%">วัน/เวลาที่เริ่มต้น</th>
                        <th width="10%">วัน/เวลาที่สิ้นสุด</th>
                        <th width="10%">ชื่อผู้จอง</th>
                        <th width="10%">วันที่จอง</th>
                        <th width="8%" align="center">&nbsp;</th>
                    </tr>
                    @if(count($reservs) > 0)
                        @foreach($reservs as $reserv)
                        <tr>
                            @if(Auth::user()->roles_id == 1 || Auth::user()->roles_id == 2)
                            <td>
                                <div class="form-group">
                                    @if($reserv->status_reservs_id == 3)

                                    @else
                                        <input type="checkbox" class="sub_chk" data-id="{{$reserv->id}}" @if($reserv->status_reservs_id == 3) style="display: none;" @endif name="subchk[]">
                                    @endif
                                </div>
                            </td>
                            @endif
                            <td>{{ $reserv->id }}</td>
                            <td><font color="@if($reserv->status->id == 1) #A0522D @elseif($reserv->status->id == 2) #5cb85c @elseif($reserv->status->id == 3) #d9534f @endif">
                                    @if($reserv->status->id == 1)
                                        <i class="fa fa-circle-o-notch" aria-hidden="true"></i>
                                    @elseif($reserv->status->id == 2)
                                        <i class="fa fa-check-square" aria-hidden="true"></i>
                                    @elseif($reserv->status->id == 3)
                                        <i class="fa fa-times-circle" aria-hidden="true"></i>
                                    @endif
                                    {{ $reserv->status->name }}
                                </font></td>
                            <td>{{ $reserv->topic }}</td>
                            <td>{{ ConvertDate($reserv->startday) }} <br> {{ ConvertTime($reserv->starttime) }}&nbsp;น.</td>
                            <td>{{ ConvertDate($reserv->endday) }} <br> {{ ConvertTime($reserv->endtime) }}&nbsp;น.</td>
                            <td>{{ $reserv->user->titles->name }}{{ $reserv->user->fullname }} </td>
                            <td>@if($reserv->created_at != NULL) {{ ConvertDateCreate($reserv->created_at) }} @endif</td>
                            <td><center><button class="btn btn-app btn-info btn-xs" onclick="javascript:window.location.href='{{ route('reserv.show',$reserv->id) }}'">
                            <i class="ace-icon fa fa-info bigger-120"></i>ดูข้อมูล</button></center></center></td>
                        </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">No Data</td>
                        </tr>
                    @endif
                </table>
                <p>ทั้งหมด {{ $reservs->total() }} รายการ</p>
                {{ $reservs->links() }}
                </div>
        </div>
	</div><!-- /.col -->
</div><!-- /.row -->

@include('layouts.inc-minicontent-bottom')
@endsection

@section('scripts')
    <script src="{{ asset('js/bootstrap-datepicker.js') }}"></script>
    <script>
	$('.date-picker').datepicker({
		autoclose: true,
		todayHighlight: true
	})
    </script>
    <script>
        //AllSelected//
        $('#all_chk').on('click', function(e) {
            if($(this).is(':checked',true))
            {
                $(".delete_all").css('display', 'block');
                $(".sub_chk").prop('checked', true);
            } else {
                $(".sub_chk").prop('checked',false);
                $(".delete_all").css('display', 'none');
            }
        });
        //One Selected//
        $(".sub_chk").on('click', function(e) {
            if($(this).is(':checked',true))
            {
                var cnt = $('[name="subchk[]"]:checked').length;

                $(".delete_all").css('display', 'block');
            } else {
                var cnt = $('[name="subchk[]"]:checked').length;
                if(cnt < 1){
                $(".delete_all").css('display', 'none');
                }
            }
        });

        $('.delete_all').on('click', function(e) {
            var allVals = [];
            $(".sub_chk:checked").each(function() {
                allVals.push($(this).attr('data-id'));
            });
            if(allVals.length <=0)
            {
                alert("Please select row.");
            }else {
                swal({
                    title: "ยืนยันการอนุมัติการจองประชุม?",
                    text: "จำนวน "+ allVals.length + " รายการ",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                    .then((willDelete) => {
                        if (willDelete) {
                            var join_selected_values = allVals.join(",");

                            $.ajax({
                                url: '{{ route("reserv.updateStatusAll") }}',
                                type: 'POST',
                                data:
                                    {
                                        _token: "{{ csrf_token() }}",
                                        ids : join_selected_values
                                    },success: function (data) {
                                    if(data.success == true){
                                        swal("ยืนยันการจองห้องเรียบร้อยแล้ว!","","success")
                                            .then(function(){
                                                location.reload();
                                            });
                                    }else {
                                        swal("Error!", "เลขที่จองนี้ ถูกยกเลิกไปแล้ว กรุณาลองใหม่อีกครั้ง!", "error")
                                            .then(function(){
                                                //location.reload();
                                            });
                                        console.log(data)
                                    }
                                },
                                error: function (data) {
                                    alert(data.responseText);
                                }
                            });

                        }
                    });
            }
            });

    </script>
@endsection