routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();

Route::group(['middleware' => 'auth'],function(){

    //Reservs//
    Route::group(['prefix' => 'reservs', 'as' => 'reserv.'], function () {
        Route::get('/view/{slug}', 'ReservController@index')->name('view');
        Route::get('/create', 'ReservController@create')->name('create');
        Route::post('/save', 'ReservController@store')->name('save');
        Route::get('/show/{id}', 'ReservController@show')->name('show');
        Route::get('/edit/{id}', 'ReservController@edit')->name('edit');
        Route::post('/update', 'ReservController@update')->name('update');
        Route::get('/export/{id}', 'ReservController@exportPDF')->name('export');
        Route::post('/updateStatus', 'ReservController@updateStatus')->name('updateStatus');
        Route::post('/updateStatusAll', 'ReservController@updateStatusAll')->name('updateStatusAll');
        Route::post('/note', 'ReservController@storeNote')->name('note');

        //Calendar//
        Route::get('/events', 'ReservController@GetEvents')->name('events');

        //ห้องประชุมย่อยจาก Rooms//
        Route::post('/childrenroom', 'ReservController@GetChildrenRooms')->name('childrenroom');
    });

    //Rooms//
    Route::group(['prefix' => 'rooms', 'as' => 'room.'], function () {
        Route::get('/view', 'RoomController@index')->name('view');
        Route::get('/create', 'RoomController@create')->name('create');
        Route::post('/save', 'RoomController@store')->name('save');
        Route::get('/edit/{id}', 'RoomController@edit')->name('edit');
        Route::post('/update', 'RoomController@update')->name('update');
        Route::get('/remove/{id}', 'RoomController@destroy')->name('remove');
    });

    //Reports//
    Route::group(['prefix' => 'reports', 'as' => 'report.'], function () {
        Route::get('/view', 'ReportController@index')->name('view');
        Route::post('/report_year', 'ReportController@report_year')->name('reportyear');
        Route::post('/report_month', 'ReportController@report_month')->name('reportmonth');
        Route::post('/report_mannul', 'ReportController@report_mannul')->name('reportmannul');
    });

    //Users//
    Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
        Route::get('/view', 'UserController@index')->name('view');
        Route::get('/create', 'UserController@create')->name('create');
        Route::post('/save', 'UserController@store')->name('save');
        Route::get('/edit/{id}', 'UserController@edit')->name('edit');
        Route::post('/update/{id}', 'UserController@update')->name('update');
        Route::post('/active', 'UserController@active')->name('active');
        Route::get('/history/{id}', 'UserController@history')->name('history');
        Route::get('/editprofile/{id}', 'UserController@editProfile')->name('editprofile');
        Route::post('/updateprofile/{id}', 'UserController@updateProfile')->name('updateprofile');
        Route::get('/setpassword/{id}', 'UserController@setPassword')->name('setpassword');
        Route::post('/active', 'UserController@enabled')->name('active');
        Route::post('/inactive', 'UserController@disabled')->name('inactive');
    });

    //Configs//
    Route::group(['prefix' => 'set_basics', 'as' => 'set_basic.'], function () {
        Route::get('/view', 'Basic\SetBasicController@index')->name('view');

        //GroupUser//
        Route::group(['prefix' => 'groupusers', 'as' => 'groupuser.'], function () {
            Route::get('/view', 'Basic\GroupUserController@index')->name('view');
            Route::get('/create', 'Basic\GroupUserController@create')->name('create');
            Route::post('/save', 'Basic\GroupUserController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\GroupUserController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\GroupUserController@update')->name('update');
        });

        //Roles//
        Route::group(['prefix' => 'roles', 'as' => 'role.'], function () {
            Route::get('/view', 'Basic\RolesController@index')->name('view');
            Route::get('/create', 'Basic\RolesController@create')->name('create');
            Route::post('/save', 'Basic\RolesController@store')->name('save');
            Route::get('/edit/{id}', 'Basic\RolesController@edit')->name('edit');
            Route::post('/update/{id}', 'Basic\RolesController@update')->name('update');
        });


    });

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/inc-menu.blade.php
<!-- Top Menu -->
<div id="navbar" class="navbar navbar-default">
    <div class="navbar-container" id="navbar-container">
        <!-- #section:basics/sidebar.mobile.toggle -->
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>
        <script type="text/javascript">
            try{ace.settings.check('navbar' , 'fixed')}catch(e){}
        </script>
        <!-- /section:basics/sidebar.mobile.toggle -->
        <div class="navbar-header pull-left">
            <!-- #section:basics/navbar.layout.brand -->
            <a href="#" class="navbar-brand">
                <small>
                    <i class="fa fa-leaf"></i>
                    ระบบจองห้องประชุม สำนักงานอาสากาชาด สภากาชาดไทย
                </small>
            </a>


            <!-- /section:basics/navbar.toggle -->
        </div>
        <!-- #section:basics/navbar.dropdown -->
        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="purple">

                <!-- #section:basics/navbar.user_menu -->
                <li class="light-blue">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <span class="user-info">
                            <small>ยินดีต้อนรับ,</small>
                            {{ Auth::user()->titles->name }} {{ Auth::user()->fullname }} <br>
                            ({{ Auth::user()->group->name }})
                        </span>

                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>

                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="{{ route('user.history', Auth::user()->id) }}">
                                <i class="ace-icon fa fa-history"></i>
                                ประวัติการจอง 
                                @php $count = App\Reserv::where('user_id', Auth::user()->id)->count(); @endphp
                                <span class="badge">{{ $count }}</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('user.editprofile', Auth::user()->id) }}">
                                <i class="ace-icon fa fa-user"></i>
                                แก้ไขข้อมูล
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="ace-icon fa fa-power-off"></i>
                                ออกจากระบบ
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>                            
                        </li>
                    </ul>
                </li>

                <!-- /section:basics/navbar.user_menu -->
            </ul>
        </div>
    </div><!-- /.navbar-container -->
</div>

<!---------------------------------------------------------------------------------------->

<!--Left Menu -->
<div class="main-container" id="main-container">
    <script type="text/javascript">
        try{ace.settings.check('main-container' , 'fixed')}catch(e){}
    </script>
        
	<script type="text/javascript">
			try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
	</script>

	  <div class="sidebar-shortcuts" id="sidebar-shortcuts">

    </div><!-- /.sidebar-shortcuts -->

    <!--Menu-->
        <!-- #section:basics/sidebar -->
        <div id="sidebar" class="sidebar responsive">
            <ul class="nav nav-list">
              @if(checkPermission(['user','officer','administrator']))
                  <li class="{{ Request::is( 'reservs/view/today', 'reservs/view/calendar', 'reservs/view/table', 'reservs/create', 'reservs/report') ? 'open' : '' }}">
                    <a href="#" class="dropdown-toggle">
                      <i class="menu-icon fa fa-bandcamp"></i>
                      <span class="menu-text"> 1.การจองห้อง </span>

                      <b class="arrow fa fa-angle-down"></b>
                    </a>

                    <b class="arrow"></b>

                    <ul class="submenu">
                      <li class="{{ Request::is( 'reservs/view/today' , 'reservs/view/calendar', 'reservs/view/table') ? 'active' : '' }}">
                        <a href="{{ url('reservs/view/today') }}">
                          <i class="menu-icon fa fa-caret-right"></i>
                          รายการการใช้ห้องประชุม
                        </a>

                        <b class="arrow"></b>
                      </li>

                      <li class="{{ Request::is( 'reservs/create') ? 'active' : '' }}">
                        <a href="{{ url('reservs/create') }}">
                          <i class="menu-icon fa fa-caret-right"></i>
                          จองห้องประชุม
                        </a>

                        <b class="arrow"></b>
                      </li>
                      <li class="{{ Request::is( 'reservs/report') ? 'active' : '' }}">
                        <a href="#">
                          <i class="menu-icon fa fa-caret-right"></i>
                          พิมพ์รายการการใช้ห้องประชุม
                        </a>
                      </li>
                    </ul>
                </li>
              @endif
              @if(checkPermission(['officer','administrator']))
                <li class="{{ Request::is( 'rooms/view', 'rooms/create') ? 'open' : '' }}">
                  <a href="#" class="dropdown-toggle">
                    <span class="menu-icon glyphicon glyphicon-flag"></span>
                    <span class="menu-text"> 2.ห้องประชุม </span>

                    <b class="arrow fa fa-angle-down"></b>
                  </a>

                  <b class="arrow"></b>

                  <ul class="submenu">
                    <li class="{{ Request::is( 'rooms/view') ? 'active' : '' }}">
                      <a href="{{ url('rooms/view') }}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        รายชื่อห้องประชุม
                      </a>

                      <b class="arrow"></b>
                    </li>

                    <li class="{{ Request::is( 'rooms/create') ? 'active' : '' }}">
                      <a href="{{ url('rooms/create') }}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        สร้างห้องประชุม
                      </a>

                      <b class="arrow"></b>
                    </li>
                  </ul>
                </li>
                <li class="{{ Request::is( 'reports/view') ? 'active' : '' }}">
                  <a href="{{ route('report.view') }}">
                    <i class="menu-icon fa fa-file-text"></i>
                    <span class="menu-text"> 3.รายงาน </span>
                  </a>
                  <b class="arrow"></b>
                </li>
              @endif
              @if(checkPermission(['administrator']))
                <li class="{{ Request::is( 'users/view', 'users/create') ? 'open' : '' }}">
                  <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-user-circle-o"></i>
                    <span class="menu-text"> 4.บัญชีผู้ใช้งาน </span>

                    <b class="arrow fa fa-angle-down"></b>
                  </a>

                  <b class="arrow"></b>

                  <ul class="submenu">
                    <li class="{{ Request::is( 'users/view') ? 'active' : '' }}">
                      <a href="{{ url('users/view') }}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        รายชื่อบัญชีผู้ใช้งาน
                      </a>

                      <b class="arrow"></b>
                    </li>

                    <li class="{{ Request::is( 'users/create') ? 'active' : '' }}">
                      <a href="{{ url('users/create') }}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        สร้างบัญชีผู้ใช้งาน
                      </a>

                      <b class="arrow"></b>
                    </li>
                  </ul>
                </li>
                <li class="{{ Request::is( 'set_basics/view') ? 'active' : '' }}">
                  <a href="{{ route('set_basic.view') }}">
                    <i class="menu-icon fa fa-cog"></i>
                    <span class="menu-text"> 5.ตั้งค่าระบบ </span>
                  </a>
    
                  <b class="arrow"></b>
                </li>
              @endif
            </ul><!-- /.nav-list -->

            <!-- #section:basics/sidebar.layout.minimize -->
            <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
                <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
            </div>

            <!-- /section:basics/sidebar.layout.minimize -->
            <script type="text/javascript">
                try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
            </script>
        </div>

resources/views/layouts/inc-minicontent-bottom.blade.php
        </div>
    </div>
</div>


</div>

resources/views/layouts/inc-minicontent-top.blade.php
<div class="main-content">
    <div class="main-content-inner">
        <div class="page-content">

resources/views/layouts/inc-scripts.blade.php
<script src="{{asset('js/jquery.js') }}"></script>
<script src="{{asset('js/bootbox.js')}}"></script>
<script src="{{asset('js/bootstrap.js')}}"></script>
<script src="{{asset('js/jquery-ui.js')}}"></script>
<script src="{{asset('js/moment.min.js')}}"></script>
<script src="{{asset('js/fullcalendar.js')}}"></script>
<script src="{{asset('js/th.js')}}"></script>
<!--Sweetalert -->
<script src="{{ asset('js/sweetalert.min.js') }}"></script>
<!-- ace scripts -->
<script src="{{asset('js/elements.scroller.js')}}"></script>
<script src="{{asset('js/elements.colorpicker.js')}}"></script>
<script src="{{asset('js/elements.fileinput.js')}}"></script>
<script src="{{asset('js/elements.typeahead.js')}}"></script>
<script src="{{asset('js/elements.wysiwyg.js')}}"></script>
<script src="{{asset('js/elements.spinner.js')}}"></script>
<script src="{{asset('js/elements.treeview.js')}}"></script>
<script src="{{asset('js/elements.wizard.js')}}"></script>
<script src="{{asset('js/elements.aside.js')}}"></script>
<script src="{{asset('js/ace.js')}}"></script>
<script src="{{asset('js/ace.ajax-content.js')}}"></script>
<script src="{{asset('js/ace.touch-drag.js')}}"></script>
<script src="{{asset('js/ace.sidebar.js')}}"></script>
<script src="{{asset('js/ace.sidebar-scroll-1.js')}}"></script>
<script src="{{asset('js/ace.submenu-hover.js')}}"></script>
<script src="{{asset('js/ace.widget-box.js')}}"></script>
<script src="{{asset('js/ace.settings.js')}}"></script>
<script src="{{asset('js/ace.settings-rtl.js')}}"></script>
<script src="{{asset('js/ace.settings-skin.js')}}"></script>
<script src="{{asset('js/ace.widget-on-reload.js')}}"></script>
<script src="{{asset('js/ace.searchbox-autocomplete.js')}}"></script>
@stack('scripts')

resources/views/layouts/inc-stylesheets.blade.php
<!-- bootstrap -->
<link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}" />
<!-- text fonts -->
<link rel="stylesheet" href="{{ asset('css/jquery-ui.custom.css') }}" />
<!-- text fonts -->
<link rel="stylesheet" href="{{ asset('css/ace-fonts.css') }}" />
<!-- fontsawesome -->
<link rel="stylesheet" href="{{ asset('css/font-awesome.css') }}"/>
<!-- Fullcalendar -->
<link rel="stylesheet" href="{{ asset('css/fullcalendar.css') }}">
<!-- ace styles -->
<link rel="stylesheet" href="{{ asset('css/ace.css') }}" class="ace-main-stylesheet" id="main-ace-style" />
<!-- inline styles related to this page -->
<!-- select2 -->
<link rel="stylesheet" href="{{ asset('css/select2.css') }}">
<link rel="stylesheet" href="{{ asset('css/select2-bootstrap.css') }}">
<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

<!--[if lte IE 8]>
<script src="../assets/js/html5shiv.js"></script>
<script src="../assets/js/respond.js"></script>
<![endif]-->
<!-- custom styles -->
<link rel="stylesheet" href="{{ asset('css/style.css') }}" class="ace-main-stylesheet" id="main-ace-style" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">

@stack('stylesheets')

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@yield('title')</title>
@include('layouts.inc-stylesheets')
@yield('stylesheets')
</head>
<body class="no-skin">
    <!-- Add Content-->
    @yield('content')
    <!-- Add Content-->

@include('layouts.inc-scripts')
@yield('scripts')
</body>
</html>